name: Check all lint
on:
  pull_request:
    branches:
      - feature/*
      - develop
      - main
jobs:
  test:
    name: Check codestyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install packages
        run: pnpm install
      - name: Prettier
        run: pnpm run lint:all
