name: Update PR Template

on:
  pull_request:
    branches:
      - feature/*
      - develop
      - main

jobs:
  update-template:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update pull_request_template.md
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        ISSUE_NUMBER=$(echo $BRANCH_NAME | grep -oP 'HOGE-\d+')
        if [[ $ISSUE_NUMBER ]]; then
          sed -i "s#https://github.com/hoge/issues/.*#https://github.com/hoge/issues/$ISSUE_NUMBER#g" .github/pull_request_template.md
          git config user.name 'GitHub Actions'
          git config user.email 'github-actions@users.noreply.github.com'
          git add .github/pull_request_template.md
          git commit -m "Update pull_request_template.md with dynamic issue URL"
          git push
        fi
