name: Update PR Template

on:
  push:
    branches:
      - HOGE-*
      - feature/*
      - develop
      - main

jobs:
  update-template:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update template with issue number
      run: |
        branch_name=${GITHUB_REF##*/}
        issue_number=$(echo $branch_name | grep -o -E '[0-9]+')
        if [[ $issue_number ]]; then
          sed -i "s|https://github.com/Hoge/issues/|https://github.com/Hoge/issues/$issue_number|" ./github/PULL_REQUEST_TEMPLATE.md
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git commit -am "Update PR template with issue number"
          git push
        fi
